### ISSUE TITLE
Error When Adding New Channel

### ISSUE THREAD

**Issue by BilliBoleMeow** [binamracode/filterbot#33]
So Deployed The Bot, added into a group made admin, added into a channel , made admin there aswell. Sent the command /add @channelusername 
Show error

2022-01-31T13:41:19.168765+00:00 app[worker.1]: Error: Required object filter of messages.SearchGlobal is undefined
2022-01-31T13:41:19.168767+00:00 app[worker.1]:     at argToBytes (/app/node_modules/telegram/tl/api.js:111:23)
2022-01-31T13:41:19.168767+00:00 app[worker.1]:     at VirtualClass.getBytes (/app/node_modules/telegram/tl/api.js:410:42)
2022-01-31T13:41:19.168768+00:00 app[worker.1]:     at new RequestState (/app/node_modules/telegram/network/RequestState.js:9:29)
2022-01-31T13:41:19.168768+00:00 app[worker.1]:     at MTProtoSender.send (/app/node_modules/telegram/network/MTProtoSender.js:197:23)
2022-01-31T13:41:19.168769+00:00 app[worker.1]:     at Object.invoke (/app/node_modules/telegram/client/users.js:27:44)
2022-01-31T13:41:19.168770+00:00 app[worker.1]:     at async _MessagesIter._loadNextChunk (/app/node_modules/telegram/client/messages.js:198:19)
2022-01-31T13:41:19.168770+00:00 app[worker.1]:     at async Object.next (/app/node_modules/telegram/requestIter.js:56:39)
2022-01-31T13:41:19.168770+00:00 app[worker.1]:     at async addFiles (file:///app/helper/addFiles.js:21:22)
2022-01-31T13:41:19.168771+00:00 app[worker.1]:     at async Object.default [as callback] (file:///app/controllers/channel/addChannel.js:42:19)
2022-01-31T13:46:49.715623+00:00 app[worker.1]: undefined
2022-01-31T13:46:49.853473+00:00 app[worker.1]: Adding @zbshdbsvdlfb in -1001758914041
2022-01-31T13:46:50.372405+00:00 app[worker.1]: Error Occured while adding channel, Please check logs for more info
2022-01-31T13:46:50.372693+00:00 app[worker.1]: Error: Required object filter of messages.SearchGlobal is undefined
2022-01-31T13:46:50.372695+00:00 app[worker.1]:     at argToBytes (/app/node_modules/telegram/tl/api.js:111:23)
2022-01-31T13:46:50.372696+00:00 app[worker.1]:     at VirtualClass.getBytes (/app/node_modules/telegram/tl/api.js:410:42)
2022-01-31T13:46:50.372696+00:00 app[worker.1]:     at new RequestState (/app/node_modules/telegram/network/RequestState.js:9:29)
2022-01-31T13:46:50.372697+00:00 app[worker.1]:     at MTProtoSender.send (/app/node_modules/telegram/network/MTProtoSender.js:197:23)
2022-01-31T13:46:50.372697+00:00 app[worker.1]:     at Object.invoke (/app/node_modules/telegram/client/users.js:27:44)
2022-01-31T13:46:50.372698+00:00 app[worker.1]:     at async _MessagesIter._loadNextChunk (/app/node_modules/telegram/client/messages.js:198:19)
2022-01-31T13:46:50.372698+00:00 app[worker.1]:     at async Object.next (/app/node_modules/telegram/requestIter.js:56:39)
2022-01-31T13:46:50.372699+00:00 app[worker.1]:     at async addFiles (file:///app/helper/addFiles.js:21:22)
2022-01-31T13:46:50.372699+00:00 app[worker.1]:     at async Object.default [as callback] (file:///app/controllers/channel/addChannel.js:42:19)

Hope this helps in debugging

**Comment by BilliBoleMeow** [comment]
Also why is there 2 type of workers, web and worker, this one is just curiousity question.

**Comment by binamracode** [comment]
Are you getting same user while using channel id instead of it's username?
If not possible solutions might be:
- Checking if the user whose String Session you created for bot is in the channel (which you want to add) or not.
- If you have more than 50 chats in the account that you are using for bot then let me know.
If it still does not help you then let me know.

> Also why is there 2 type of workers, web and worker, this one is just curiousity question.
There is no need of web worker for this bot. If you used "Deploy to Heroku" button to deploy your button then you will surely have this issue. You have to turn off web worker to fix the issue created by this. I don't want to have web worker, I tried a lot to remove it but unfortunately looks like Heroku adds by default for apps created using nodejs buildpacks.

**Comment by BilliBoleMeow** [comment]
I have the user in the channel whoes session string i am using.
I only have a group and a channel and a bot in this account for testing.
Using /add @channelusername  gives error 
But using /add channelid works f9

**Comment by binamracode** [comment]
Thanks for letting me know, I had made this bot by keeping id in mind as most of the times you might have your channel private. I will look into implementing channel username too.

**Comment by BilliBoleMeow** [comment]
i will check if heroku issue can be fixed with heroku.yml since it not picking up the Lrocfile

**Comment by BilliBoleMeow** [comment]
Not working even with heroku.yml

Also a new bug
If we don't set a required chat yo join var, it doesn't send the file. Keeps asking to join a chat to get file.

**Comment by binamracode** [comment]
Sorry that I missed your message, and also thanks for letting me know. I will surely fix it soon.

**Comment by binamracode** [comment]
7b08878e66d3ec68f5b9c086f40b17c70fcde8d8 should fix that issue
